{% set name = "nwchem" %}
{% set version = "7.2.0" %}
{% set hash = "d0d141fd" %}
{% set date = "2023-03-10" %}

{% set armci_network = armci_network or 'mpi_ts' %}
{% set build = 4 %}
{% if armci_network  == 'mpi_ts' %}
# prioritize 'nompi' variant via build number
{% set build = build + 1000 %}
{% endif %}
{% set armci_prefix = armci_network %}




package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nwchemgit/nwchem/releases/download/v{{ version }}-release/nwchem-{{ version }}-release.revision-{{ hash }}-src.{{ date }}.tar.bz2
  sha256: f756073ab3206571a22ec26cc95dac674fed9c4c959f444b8a97df059ffa3456
  patches:
    - ibo32_source.patch
    - strip_compiler.patch
    - build_simint.patch
    - earlyexit.patch
    - qalargemem.patch
  
build:
  number: {{ build }} 
  skip: true  # [win]
  string: py{{ CONDA_PY }}_{{ armci_prefix }}_h{{ PKG_HASH }}_{{ build }}
  script_env:
    - CONDA_FORGE_DOCKER_RUN_ARGS="--shm-size=256m"
requirements:
  build:
    - cmake >=3.21
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make
    - gnuconfig
    - sed
    - file
    - {{ mpi }}
  host:
    - {{ mpi }}
    - openblas
    - scalapack
    - python
    - libxc
    - openssh
  run:
    - {{ mpi }}
    - openblas
    - libopenblas
    - scalapack
    - python

test:
    # note: test files are included in the conda package
    # avoid shipping more than necessary (test suite is large!)
  source_files:
    - QA/run*
    - QA/do*
    - QA/nwpa*
    - QA/tests/h2o_opt
    - QA/tests/dft_he2+
    - QA/tests/small_intchk
    - QA/tests/h2o_dk
    - QA/tests/cosmo_h2o_dft
    - QA/tests/pyqa3
    - QA/tests/tddft_h2o
    - QA/tests/tddft_n2+
    - QA/tests/tddft_ac_co
    - QA/tests/hi_zora_sf
    - QA/tests/prop_ch3f
    - QA/tests/h2_bnl
    - QA/tests/h2o_bnl
    - QA/tests/h2o-camb3lyp-pol
    - QA/tests/h2o-cambeckehh
    - QA/tests/h2o-campbe0
    - QA/tests/h2o-lcpbe
    - QA/tests/o2_bnl
    - QA/tests/o2_hfattn
    - QA/tests/dmo_tddft_cd
    - QA/tests/dmo_tddft_cd_velocity
    - QA/tests/h2o-response
    - QA/tests/h2o2-response
    - QA/tests/h2o2-response-uhf
    - QA/tests/h2o2-response-uhf-damping
    - QA/tests/h2o2-prop-notrans
    - QA/tests/ch3radical_unrot
    - QA/tests/localize-ibo-aa
    - QA/tests/x2c-h2se
    - QA/tests/hg-1e-hfc-x2c
    - QA/tests/dft_he2p_wb97
  requires:
    - perl

about:
  home: https://nwchemgit.github.io
  license: ECL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Open Source High-Performance Computational Chemistry
  description: |
    NWChem is actively developed by a consortium of developers and maintained by the Environmental Molecular Sciences Laboratory (EMSL), a US DOE Office of Science User Facility located at the Pacific Northwest National Laboratory (PNNL) in Washington State.
  doc_url: https://nwchemgit.github.io/
  dev_url: https://github.com/nwchemgit/nwchem

extra:
  recipe-maintainers:
    - ltalirz
    - edoapra
