context:
  name: "nwchem"
  #version: "7.3.0"
  version: "nightly"
  hash: "3a79daa2"
  release_tag: "v" + version + "-release"
  user: "edoapra"
  date: "2025-10-19"
  build: 1 
  armci_network: armci_network or 'mpi_ts'
  if: match(armci_network, 'mpi_ts')
  then:
    # prioritize 'nompi' variant via build number
    build: build + 1000
  armci_prefix: armci_network
  if: match(armci_network, 'mpi3')
  then:
  # get six digits armci_prefix
  armci_prefix: 'mpi__3'

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ user }}/nwchem/releases/download/{{ release_tag }}/nwchem-{{ version }}-release.revision-{{ hash }}-src.{{ date }}.tar.bz2
  sha256: 10b10b05d160a1500a5eda82bf001431c0e21cacc2440576f29c303ec3d34e6c
  patches:
    - qalargemem.patch
    - conda_nwchemrc.patch
    - tblite_omp.patch
 
build:
  number: {{ build }} 
  skip:
    - win
    - py==39 and osx
  string:
    - py{{ CONDA_PY }}_{{ armci_prefix }}_h{{ PKG_HASH }}_{{ build }}
  script_env:
    - CONDA_FORGE_DOCKER_RUN_ARGS="--shm-size=256m"
requirements:
  build:
    - cmake >=3.21
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    if: build_platform != target_platform
    then:
      - python  
      - cross-python_{{ target_platform }} 
    - make
    - gnuconfig
    - sed
    - {{ mpi }}
    if: linux
    then:
      - libgomp
    if: osx
    then:
      - llvm-openmp
  host:
    - {{ mpi }}
    - openblas
    - scalapack
    - python
    - libxc *.* *cpu*
    - openssh
    if: not (linux64 or osx)
    then:
      - plumed
    if: osx
    then:
      - llvm-openmp
    if: linux
    then:
      - libgomp
      if: py<39
      then:
        - libxcrypt
  run:
    - {{ mpi }}
    - openblas
    - libopenblas
    - scalapack
    - python
    if: not (linux64 or osx)]
    then:
      - plumed
    if: osx
    then:
      - llvm-openmp
    if: linux
    then:
      - libgomp
      - openssh

tests:
    # note: test files are included in the conda package
    # avoid shipping more than necessary (test suite is large!)
  file:
    source:
      - QA/doaf*
      - QA/run*
      - QA/*sh
      - QA/nwpa*
      - QA/tests/h2o_opt
      - QA/tests/dft_he2+
      - QA/tests/small_intchk
      - QA/tests/h2o_dk
      - QA/tests/cosmo_h2o_dft
      - QA/tests/pyqa3
      - QA/tests/tddft_h2o
      - QA/tests/tddft_n2+
      - QA/tests/tddft_ac_co
      - QA/tests/hi_zora_sf
      - QA/tests/prop_ch3f
      - QA/tests/h2_bnl
      - QA/tests/h2o_bnl
      - QA/tests/h2o-camb3lyp-pol
      - QA/tests/h2o-cambeckehh
      - QA/tests/h2o-campbe0
      - QA/tests/h2o-lcpbe
      - QA/tests/o2_bnl
      - QA/tests/o2_hfattn
      - QA/tests/dmo_tddft_cd
      - QA/tests/dmo_tddft_cd_velocity
      - QA/tests/h2o-response
      - QA/tests/h2o2-response
      - QA/tests/h2o2-response-uhf
      - QA/tests/h2o2-response-uhf-damping
      - QA/tests/h2o2-prop-notrans
      - QA/tests/ch3radical_unrot
      - QA/tests/localize-ibo-aa
      - QA/tests/localize-ibo-allyl
      - QA/tests/localize-pm-allyl
      - QA/tests/x2c-h2se
      - QA/tests/hg-1e-hfc-x2c
      - QA/tests/dft_he2p_wb97
  requirements:
    run:
      - perl

about:
  home: https://nwchemgit.github.io
  license: ECL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Open Source High-Performance Computational Chemistry
  description: |
    NWChem is actively developed by a consortium of developers and maintained by the Environmental Molecular Sciences Laboratory (EMSL), a US DOE Office of Science User Facility located at the Pacific Northwest National Laboratory (PNNL) in Washington State.
  doc_url: https://nwchemgit.github.io/
  dev_url: https://github.com/nwchemgit/nwchem

extra:
  recipe-maintainers:
    - ltalirz
    - edoapra
